version: "3.3"
services:
  api_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8682:8682"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
    depends_on:
      - mongo_db
    networks:
      - tweet_net
  mongo_db:
    container_name: "mongocont"
    image: "mongo:4.4.3"
    volumes: 
      - ./mongo_data_container:/data/db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - tweet_net
networks: 
  tweet_net:
    driver: bridge
